src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::group(['middleware' => ['auth','role'], 'roles' => ['admin', 'user']], function (){
    Route::view('/', 'home');
    Route::resource('projects',"ProjectsController");
    Route::get("/items_project/{project_id}","ItemsController@show")->name("project_items"); //change the show route.
    Route::resource('items',"ItemsController");
    Route::get("/api/list_item_json","ApiController@list_items_json");
    Route::get("/api/check_item","ApiController@check_item");
});

Route::group(['middleware' => ['auth','role'], 'roles' => ['admin']], function (){
    Route::resource('users', "UsersController");
    Route::get("/trash","TrashController@manage")->name("trash");
    Route::get("/trash/ui/{item}","TrashController@unerase_item")->name("trash_unerase_item");
    Route::get("/trash/up/{project}","TrashController@unerase_project")->name("trash_unerase_project");
    Route::delete("/trash/empty","TrashController@empty")->name("trash_empty");
    Route::delete("/trash/ri/{item}","TrashController@remove_item")->name("trash_item_remove");
    Route::delete("/trash/rp/{project}","TrashController@remove_project")->name("trash_project_remove");
});

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

src/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <!-- CSS-->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,700">
    <!-- Favicon-->
    <link rel="shortcut icon" href="img/favicon.ico">
    <!-- Font Awesome CDN-->
    <script src="https://use.fontawesome.com/99347ac47f.js"></script>
    <!-- Font Icons CSS-->
    <link rel="stylesheet" href="https://file.myfontastic.com/da58YPMQ7U5HY8Rb6UxkNf/icons.css">
    <!-- Jquery CDN -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <!--Angular from google cdn -->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.6/angular.min.js"></script>
</head>
<body>
    @yield('content')
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

src/resources/views/layouts/page.blade.php
@extends('layouts.app')

@section('content')
<div class="page">
    <!-- Main Navbar-->
    <header class="header">
    <nav class="navbar">
        <div class="container-fluid">
        <div class="navbar-holder d-flex align-items-center justify-content-between">
            <!-- Navbar Header-->
            <div class="navbar-header">
            <!-- Navbar Brand --><a href="/" class="navbar-brand">
                <div class="brand-text brand-big hidden-lg-down"><span>BackLink</span><strong>Checker</strong></div>
                <div class="brand-text brand-small"><strong>BLC</strong></div></a>
            <!-- Toggle Button--><a id="toggle-btn" href="#" class="menu-btn active"><span></span><span></span><span></span></a>
            </div>
            <!-- Navbar Menu -->
            <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
            <!-- User profile -->
            <li class="nav-item">{{ Auth::user()->name }}</li>
            <!-- Logout    -->
            <li class="nav-item"><a href="/logout" class="nav-link logout"><i class="fa fa-sign-out"></i></a></li>
            </ul>
        </div>
        </div>
    </nav>
    </header>
    <div class="page-content d-flex align-items-stretch">
        <!-- Side Navbar -->
        <nav class="side-navbar">
            <!-- Sidebar Header-->

            <!-- Sidebar Navidation Menus-->
            <ul class="list-unstyled">
            <li><a href="/"><i class="icon-home"></i>Home</a></li>
            @if(Auth::user()->hasRole("admin"))
                <li><a href="{{route('users.index') }}"> <i class="fa fa-users"></i>Users </a></li>
                <li><a href="{{route('trash')}}"> <i class="fa fa-trash"></i>Trash </a></li>
            @endif
            <li><a href="{{route('projects.index') }}"> <i class="icon-interface-windows"></i>Projects</a></li>
            <li><a href="{{route('items.index') }}"> <i class="fa fa-external-link"></i>Items</a></li>
        </nav>
        <div class="content-inner">
         <?php $notice = \Request::input("notice",false); ?>
            <div class="row">
                @if($notice)
                  <div class="col-md-12">
                    <div class="alert alert-info alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{$notice}}
                    </div>
                  </div>
                @endif
            </div>
            <!-- Page Header-->
            <header class="page-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-10">
                        <h2 class="no-margin-bottom">@yield('page-title')</h2>
                    </div>
                    <div class="col-sm-2">
                        @yield('actions')
                    </div>
                </div>
            </div>
            </header>
            <br>    
            @yield('page-content')
            <br>
        </div>
    </div>
</div>
<!-- Page Footer-->
<footer class="main-footer">
<div class="container-fluid">
    <div class="row">
    <div class="col-sm-6">
        <p>Zaitek &copy; 2017</p>
    </div>
    <div class="col-sm-6 text-right">
        <p>Developed by <a href="http://www.elcansoftware.com">Elcan Software</a> - Design based on <a href="https://bootstrapious.com/admin-templates" class="external">Bootstrapious</a></p>
        <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)--></p>
    </div>
    </div>
</div>
</footer>
@endsection